name: lomax

services:
  floci:
    image: floci/floci:latest
    container_name: floci
    user: root
    ports:
      - "4566:4566"
      - "7001-7010:7001-7010"
    environment:
      FLOCI_HOSTNAME: floci
      FLOCI_STORAGE_MODE: persistent
      FLOCI_STORAGE_PERSISTENT_PATH: /app/data
      FLOCI_SERVICES_DOCKER_NETWORK: lomax-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - floci-data:/app/data
    networks:
      - lomax-net
  backend:
    build: ./backend
    image: lomax-backend:dev
    container_name: lomax-backend
    depends_on:
      - floci
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      DB_HOST: floci
      DB_PORT: "7001"
      DB_USER: lomax_admin
      DB_PASSWORD: LomaxAdmin2026
      DB_NAME: lomax
      AWS_ENDPOINT_URL: http://floci:4566
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      BUCKET_ORIGINALES: lomax-originales
      BUCKET_MINIATURAS: lomax-miniaturas
      TABLA_ATRIBUTOS: ProductosAtributos
      LAMBDA_FUNCION: generar-miniatura
    networks:
      - lomax-net
    restart: unless-stopped
  frontend:
    build: ./frontend
    image: lomax-frontend:dev
    container_name: lomax-frontend
    networks:
      - lomax-net
    restart: unless-stopped
  proxy:
    image: nginx:1.27-alpine
    container_name: lomax-proxy
    depends_on:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - lomax-net
    restart: unless-stopped

networks:
  lomax-net:
    name: lomax-net

volumes:
  floci-data:
    name: lomax-floci-data