CREATE TABLE IF NOT EXISTS categorias (
    categoria_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR(60) NOT NULL UNIQUE,
    CONSTRAINT categoria_nombre_no_vacio CHECK (length(trim(nombre)) > 0)
);

CREATE TABLE IF NOT EXISTS productos (
    producto_id    UUID PRIMARY KEY,
    codigo         VARCHAR(20)   NOT NULL UNIQUE,
    nombre         VARCHAR(120)  NOT NULL,
    descripcion    TEXT          NOT NULL,
    precio         NUMERIC(10,2) NOT NULL,
    categoria_id   INT           NOT NULL REFERENCES categorias (categoria_id),
    fecha_registro TIMESTAMPTZ   NOT NULL DEFAULT now(),
    estado         VARCHAR(10)   NOT NULL DEFAULT 'PENDIENTE',
    CONSTRAINT producto_precio_no_negativo CHECK (precio >= 0),
    CONSTRAINT producto_estado_valido      CHECK (estado IN ('PENDIENTE', 'PUBLICADO')),
    CONSTRAINT producto_codigo_no_vacio    CHECK (length(trim(codigo)) > 0),
    CONSTRAINT producto_nombre_no_vacio    CHECK (length(trim(nombre)) > 0),
    CONSTRAINT producto_desc_no_vacia      CHECK (length(trim(descripcion)) > 0)
);

CREATE INDEX IF NOT EXISTS idx_productos_categoria ON productos (categoria_id);
CREATE INDEX IF NOT EXISTS idx_productos_estado    ON productos (estado);